### ISSUE TITLE
axios 공통api셋팅

### ISSUE THREAD

**Issue by hyuntae94** [fe5-team6-project/withSix#6]
apis폴더에 axios 코드분리하는  test예제 작성해놓았습니다.~~~확인해주세용
d71980d

_Originally posted by @hyuntae94 in https://github.com/fe5-team6-project/withSix/issues/3#issuecomment-1590343198_

**Comment by haileyham** [comment]
확인했습니다! 중복되는 코드들을 발견했는데 혹시 리팩토링 가능하실까요?!

**Comment by hyuntae94** [comment]
의견감사합니다 저도 중복된 코드들을 발견해서 리팩토링 검토중입니다 같이고민해봐요~~

**Comment by haileyham** [comment]
**[issue 마감 전, 정리사항]**
1. - [ ] 위의 커밋 내용대로 axios api 공통요소들 셋팅 완료했습니다.
2a782f8

2. - [ ] 이미지 업로드 시, formData를 사용하여 데이터를 보낼 때는 별도로 Content-type: multipart/form-data를 설정할 필요가 없으므로 해당 부분 삭제 완료하였습니다. 이미지의 경우 urlApi 공통으로 사용하면 됩니다.
f8bf015

3. -[ ] 이미지 업로드 시, formData를 사용하여 API 전송하고 데이터 응답 받은 내용 서버 url 변경 시, 아래 처럼 코드 작성 참고 하시면 됩니다. 
```
        const res = await urlApi.post(`/image/uploadfile`, formData);
        const fileName = res.data.filename;
        const imageUrl = "https://api.mandarin.weniv.co.kr/" + fileName;
 ```
9b1d2c1
3번 이슈 해결과정 : https://github.com/fe5-team6-project/withSix/issues/34

**Comment by haileyham** [comment]
[URL 예악어로 인하여 URL -> BaseURL로 변경](https://github.com/fe5-team6-project/withSix/commit/e255ba6085637cef2bcf1bbd42d7717bbbfc2c7f)
