### ISSUE TITLE
유저 프로필 팔로우 버튼 클릭 관련 이슈

### ISSUE THREAD

**Issue by UngHeung** [fe5-team6-project/withSix#99]
팔로우 버튼을 컴포넌트로 불러오도록 하게되면서 생긴 이슈

1. 유저 정보를 통신으로 가져옴으로써 초기값 설정이 어려움
2. 초기값 설정이 되지 않음으로 인해 팔로우 여부에 따른 출력 값 변경이 어려워짐
3. 컴포넌트에 온클릭 이벤트가 먹히지 않음

**Comment by UngHeung** [comment]
1. 프로필 사진 클릭 시 해당 유저 정보 리덕스 상태 업로드해서 초기값을 바로 불러올 수 있도록 수정
2. 온클릭을 버튼 바깥 요소에 부여함

**Comment by UngHeung** [comment]
1. 프로필 사진 클릭 시 해당 유저 정보 리덕스 상태 업로드해서 초기값을 바로 불러올 수 있도록 수정
2. 온클릭 이벤트를 버튼 바깥 요소에 부여함

**Comment by haileyham** [comment]
유저 프로필 코드 변경으로 인하여 follow button 컴포넌트 코드 수정하고, 이후 작업들도 진행했습니다~
